import type { Section } from "@/components/IntakeForm";

export const ECOMMERCE_SECTIONS: Section[] = [
  {
    title: "Business info",
    subtitle: "The basics about your store.",
    fields: [
      {
        id: "business_name",
        label: "Business / store name",
        type: "text",
        required: true,
        placeholder: "e.g. Bloom & Co.",
      },
      {
        id: "phone",
        label: "Phone number",
        type: "tel",
        required: true,
        placeholder: "(555) 123-4567",
      },
      {
        id: "email",
        label: "Business email",
        type: "email",
        required: true,
        placeholder: "you@yourstore.com",
      },
      {
        id: "business_type",
        label: "What do you sell?",
        type: "text",
        required: true,
        placeholder: "e.g. Handmade candles, apparel",
      },
      {
        id: "address",
        label: "Business address",
        type: "text",
        required: true,
        hint: "Required for tax and store settings, even if you're online-only.",
        placeholder: "123 Main St, City, State, ZIP",
      },
    ],
  },
  {
    title: "Your content",
    subtitle: "What you're providing before we can build.",
    notice:
      "You must supply all content before your store can launch. We do not write copy, source photos, or design logos.",
    fields: [
      {
        id: "logo_ready",
        label: "Do you have a logo ready to send?",
        type: "radio",
        required: true,
        options: [
          "Yes — I'll send the file (PNG or SVG preferred)",
          "No — I need to get one made before launch",
        ],
      },
      {
        id: "photos_ready",
        label: "Do you have product photos ready?",
        type: "radio",
        required: true,
        hint: "Clean product shots or lifestyle images. We do not source or shoot photos.",
        options: [
          "Yes — I'll send them",
          "No — I'll have them ready before launch",
          "Partially — some products have photos, some don't yet",
        ],
      },
      {
        id: "copy_ready",
        label: "Do you have written product descriptions ready?",
        type: "radio",
        required: true,
        hint: "Each product needs a title, description, and price at minimum.",
        options: ["Yes — I'll send them", "No — I'll write them before launch"],
      },
      {
        id: "content_deadline",
        label: "Content delivery date",
        type: "text",
        required: false,
        hint: "What date can you have everything (logo, photos, product info) to us by? We can't start building until we have it.",
        placeholder: "e.g. By March 15",
      },
    ],
  },
  {
    title: "Products & catalog",
    subtitle: "Tell us about your product lineup.",
    fields: [
      {
        id: "product_count",
        label: "Approx. number of products",
        type: "number",
        required: true,
        placeholder: "e.g. 25",
      },
      {
        id: "collection_count",
        label: "Number of product categories",
        type: "number",
        required: false,
        hint: "e.g. Candles, Accessories, Bundles.",
        placeholder: "e.g. 4",
      },
      {
        id: "variants",
        label: "Do your products have options or variants?",
        type: "radio",
        required: true,
        hint: "e.g. size, color, scent, material — anything where the same product comes in different versions.",
        options: ["Yes", "No", "Some do, some don't"],
      },
      {
        id: "variant_details",
        label: "Describe your product options",
        type: "text",
        required: false,
        hint: 'e.g. "T-shirts come in S / M / L / XL and 6 colors." Leave blank if no variants.',
        placeholder: "e.g. Size (S/M/L/XL) and Color (6 options)",
      },
      {
        id: "catalog_ready",
        label: "Do you have a product list or data file ready?",
        type: "radio",
        required: true,
        hint: "A spreadsheet or existing product list speeds things up considerably.",
        options: [
          "Yes — I'll send a spreadsheet or file",
          "No — I'll provide product details manually",
          "I'm moving from an existing store — products can be exported",
        ],
      },
    ],
  },
  {
    title: "Payments & checkout",
    subtitle: "How customers will pay in your store.",
    fields: [
      {
        id: "payment_methods",
        label: "Which payment methods do you want to accept?",
        type: "checkbox",
        required: true,
        hint: "Select all that apply.",
        options: [
          "Credit and debit cards",
          "PayPal",
          "Apple Pay / Google Pay",
          "Buy now, pay later (e.g. Afterpay, Klarna)",
          "Not sure — use whatever's standard",
        ],
      },
      {
        id: "sales_tax",
        label: "Do you need to collect sales tax?",
        type: "radio",
        required: true,
        hint: "We can configure automatic tax calculation. You're responsible for your own filings.",
        options: ["Yes", "No", "Not sure — I'll check with my accountant"],
      },
    ],
  },
  {
    title: "Shipping & fulfillment",
    subtitle: "How orders get from you to your customers.",
    fields: [
      {
        id: "shipping_zones",
        label: "Where do you ship?",
        type: "radio",
        required: true,
        options: [
          "US only",
          "US + Canada",
          "Worldwide",
          "Local delivery or pickup only",
        ],
      },
      {
        id: "shipping_rates",
        label: "How do you want to charge for shipping?",
        type: "radio",
        required: true,
        options: [
          "Flat rate (e.g. $5.99 per order)",
          "Free shipping on all orders",
          "Free over a threshold (e.g. free over $50)",
          "Carrier-calculated rates (USPS, UPS, FedEx, DHL)",
          "Not sure — let's talk about it",
        ],
      },
      {
        id: "flat_rate_amount",
        label: "Flat rate or free threshold amount",
        type: "text",
        required: false,
        hint: 'If applicable — e.g. "$5.99" or "free over $75".',
        placeholder: "e.g. $5.99 flat / free over $75",
      },
      {
        id: "local_pickup",
        label: "Do you need a local pickup option?",
        type: "radio",
        required: true,
        options: ["Yes", "No"],
      },
      {
        id: "fulfillment",
        label: "How do you fulfill orders?",
        type: "radio",
        required: true,
        options: [
          "I pack and ship myself",
          "Third-party fulfillment warehouse (3PL)",
          "Dropshipping — supplier ships directly to customer",
          "Print-on-demand (e.g. Printful, Printify)",
        ],
      },
      {
        id: "fulfillment_details",
        label: "Fulfillment provider or supplier name",
        type: "text",
        required: false,
        hint: "If using a 3PL, dropship supplier, or print-on-demand service, let us know which one.",
        placeholder: "e.g. ShipBob, Printful, DSers",
      },
    ],
  },
  {
    title: "Store features & pages",
    subtitle: "What your store needs to do.",
    fields: [
      {
        id: "pages",
        label: "Which pages do you need?",
        type: "checkbox",
        required: true,
        hint: "Select all that apply.",
        options: [
          "Home",
          "Shop / all products",
          "About",
          "Contact",
          "FAQ",
          "Shipping & returns policy",
          "Blog",
          "Wholesale / trade",
        ],
      },
      {
        id: "features",
        label: "Which extra features do you need?",
        type: "checkbox",
        required: true,
        hint: "Select all that apply.",
        options: [
          "Customer accounts",
          "Product reviews",
          "Discount codes",
          "Gift cards",
          "Email marketing integration",
          "Abandoned cart recovery",
          "Wishlists",
          "Subscriptions / recurring orders",
          "Loyalty & rewards program",
        ],
      },
      {
        id: "existing_tools",
        label: "Tools or software you currently use",
        type: "text",
        required: false,
        hint: "e.g. Klaviyo, Mailchimp, QuickBooks, ShipStation. We'll check what we can connect.",
        placeholder: "List any tools you already use",
      },
    ],
  },
  {
    title: "Domain & access",
    subtitle: "Your web presence and migration details.",
    fields: [
      {
        id: "domain",
        label: "Do you already own a domain?",
        type: "radio",
        required: true,
        options: ["Yes — I own one", "No — I need one purchased", "Not sure"],
      },
      {
        id: "domain_name",
        label: "Domain name if you have one",
        type: "text",
        required: false,
        placeholder: "e.g. bloomandco.com",
      },
      {
        id: "migration",
        label: "Are you moving from an existing store?",
        type: "radio",
        required: true,
        options: [
          "No — this is a brand new store",
          "Yes — I'm moving from another platform",
          "Yes — I'm rebuilding an existing store",
        ],
      },
      {
        id: "migration_platform",
        label: "If moving from an existing store, where is it currently?",
        type: "text",
        required: false,
        placeholder: "e.g. Etsy, Squarespace, WooCommerce, BigCommerce",
      },
      {
        id: "instagram",
        label: "Instagram URL",
        type: "text",
        required: false,
        placeholder: "Instagram URL",
      },
      {
        id: "facebook",
        label: "Facebook URL",
        type: "text",
        required: false,
        placeholder: "Facebook URL",
      },
      {
        id: "tiktok",
        label: "TikTok URL",
        type: "text",
        required: false,
        placeholder: "TikTok URL",
      },
      {
        id: "pinterest",
        label: "Pinterest URL",
        type: "text",
        required: false,
        placeholder: "Pinterest URL",
      },
      {
        id: "other_social",
        label: "Other social profiles",
        type: "text",
        required: false,
        placeholder: "Other (YouTube, LinkedIn...)",
      },
    ],
  },
  {
    title: "Style preferences",
    subtitle: "Help us match the look and feel you're going for.",
    fields: [
      {
        id: "style_inspo",
        label: "A store or website whose look you like",
        type: "text",
        required: false,
        hint: "Drop a URL. Helps us match the vibe you're going for.",
        placeholder: "https://...",
      },
      {
        id: "brand_colors",
        label: "Brand colors",
        type: "text",
        required: false,
        placeholder: "e.g. Sage green and cream, or #8FBC8F",
      },
      {
        id: "anything_else",
        label: "Anything else we should know?",
        type: "textarea",
        required: false,
        hint: "Special requests, things to avoid, hard launch deadline, etc.",
        placeholder: "Type here...",
      },
    ],
  },
];
